local ffi=require('ffi')
local S=assert(loadfile(ROOT..'/src/snapshot.lua'))()
local blocks={}
local function alloc(n)
    local b=ffi.new('uint8_t[?]',n);blocks[#blocks+1]={b,n}
    return tonumber(ffi.cast('uintptr_t',b))
end
local function put(a,b)ffi.copy(ffi.cast('void *',a),b,#b)end
local function word(a,v)put(a,ffi.string(ffi.new('uint32_t[1]',v),4))end
local function ptr(a,v)put(a,ffi.string(ffi.new('uint64_t[1]',v),8))end
local function hash(a,s)put(a,(s:gsub('..',function(x)return string.char(tonumber(x,16))end)):reverse())end
local function entity(a,h,id,ref)
    hash(a,h);word(a+8,id);word(a+16,ref);word(a+20,1)
end
local function map(a,id,index)
    local data=alloc(64);ffi.fill(ffi.cast('void *',data),64,255)
    ptr(a,data);word(a+8,8);word(a+12,0xffffffff);word(a+16,1)
    word(data+(id%8)*8,id);word(data+(id%8)*8+4,index)
end
local game=alloc(0x2770000)
local function manager(rva,n)local a=alloc(n or 65536);ptr(game+rva,a);return a end
local mode=manager(0x276c3d0);word(mode+8,1);word(mode+0x40,1)
local player=manager(0x276c190);word(player+0x84,1);word(player+0x88,1);word(player+0x3a8,11)
local owner=manager(0x276f0c0,0xf40000);map(owner+0xf21a88,11,0)
local avatar=owner+0xf31ad8;entity(avatar,'4d1c334d294dfa97',101,11)
local eq=manager(0x276c468);map(eq+40,101,0)
local eqa=alloc(8);ptr(eq+64,eqa);ptr(eqa,avatar)
local eqr=alloc(48);ptr(eq+80,eqr);word(eqr+12,102)
local backpack=alloc(24);entity(backpack,'af9b683ccb6ddc02',102,12)
local bp=manager(0x276c318);word(bp+0x10,1)
local bpa,bpl=alloc(8),alloc(8);ptr(bp+0x38,bpa);ptr(bpa,backpack);ptr(bp+0x50,bpl);word(bpl+4,13)
local attach=manager(0x276cad0);map(attach+32,102,0)
local ar=alloc(48);ptr(attach+64,ar);word(ar+4,101)
local drone=alloc(24);entity(drone,'5beec97f4c7f4ae9',103,13)
local targeting=manager(0x276ca40);word(targeting+308,1);word(targeting+320,1);word(targeting+324,1)
map(targeting+336,103,0)
local ta,aim=alloc(8),alloc(208);ptr(targeting+360,ta);ptr(ta,drone);ptr(targeting+376,aim);word(aim,201)
local behavior=manager(0x276c470);word(behavior+32,1);map(behavior+64,103,0)
local be,br=alloc(8),alloc(496);ptr(behavior+88,be);ptr(be,drone);ptr(behavior+96,br)
word(br,189);word(br+8,7);word(br+24,201);word(br+96,1);word(br+104,103);word(br+120,1);ptr(br+152,1000010)
local perception=manager(0x276c270);map(perception+48,103,0)
local pe,pr=alloc(8),alloc(0x13f8);ptr(perception+72,pe);ptr(pe,drone);ptr(perception+80,pr)
word(pr,1);word(pr+8,2);word(pr+0x310,2)
for i=0,1 do
    local c=pr+0x318+i*80;word(c,201+i);put(c+68,ffi.string(ffi.new('float[1]',1),4));word(c+72,1);word(c+76,4)
end
local clock=manager(0x276c068);ptr(clock+24,1000000)
local faction=manager(0x276c9c8,80000)
map(faction+73808,201,0)
local fmap=ffi.new('uint64_t[1]');ffi.copy(fmap,ffi.cast('void *',faction+73808),8)
word(tonumber(fmap[0])+(202%8)*8,202);word(tonumber(fmap[0])+(202%8)*8+4,1)
local fa,enemy1,enemy2=alloc(16),alloc(24),alloc(24)
ptr(faction+73832,fa);ptr(fa,enemy1);ptr(fa+8,enemy2)
entity(enemy1,'0000000000000001',201,21);entity(enemy2,'0000000000000001',202,22)
local api={read=function(a,n)
    for _,b in ipairs(blocks)do
        local start=tonumber(ffi.cast('uintptr_t',b[1]))
        if a>=start and a+n<=start+b[2] then return ffi.string(ffi.cast('void *',a),n)end
    end
end,pointer=function(bytes)
    local p=ffi.new('uint64_t[1]');ffi.copy(p,bytes,8);local n=tonumber(p[0]);return n~=0 and n or nil
end}
local passed=0
local function test(name,fn)fn();passed=passed+1;print('PASS '..name)end
test('complete local laser ownership chain and candidate decoding',function()
    local s=S.read(api,game);assert(s.id==103 and s.target==201 and s.synced and #s.candidates==2)
    assert(s.candidates[1].eligible and s.candidates[2].eligible and s.candidates[1].valid())
end)
test('gas backpack is rejected',function()
    hash(backpack,'bffcb4cd971a8eda');local s,why=S.read(api,game);assert(not s and why=='not_laser_backpack')
    hash(backpack,'af9b683ccb6ddc02')
end)
test('another players equipment is rejected',function()
    word(ar+4,999);local s,why=S.read(api,game);assert(not s and why=='pack_holder_mismatch');word(ar+4,101)
end)
test('shared perception is rejected',function()
    word(br+104,999);assert(not pcall(S.read,api,game));word(br+104,103)
end)
test('invalid candidate counts fail closed',function()
    word(pr+0x310,17);assert(not pcall(S.read,api,game));word(pr+0x310,2)
end)
test('changed candidate identity invalidates its lease',function()
    local s=S.read(api,game);word(pr+0x318,999);assert(s.candidates[1].valid()==false);word(pr+0x318,201)
end)
test('faction suppression makes candidates ineligible',function()
    word(pr+0x318+76,0);local s=S.read(api,game);assert(not s.candidates[1].eligible and s.candidates[2].eligible)
    word(pr+0x318+76,4)
end)
test('target ID reuse invalidates restoration even if its candidate slot is unchanged',function()
    local s=S.read(api,game);word(enemy1+16,77);assert(s.candidates[1].valid()==false)
    assert(s.candidates[2].valid()==true);word(enemy1+16,21)
end)
test('other candidate count changes do not abandon a valid restore',function()
    local s=S.read(api,game);word(pr+0x818,1)
    assert(S.matches(api,s.guards)==false and s.candidates[1].valid()==true and s.valid()==true)
    word(pr+0x818,0)
end)
test('equipment changes do not abandon existing drone data restoration',function()
    local s=S.read(api,game);word(eqr,999)
    assert(S.matches(api,s.guards)==false and s.candidates[1].valid()==true and s.valid()==true)
    word(eqr,0)
end)
test('missing startup manager waits and recovers when the manager appears',function()
    ptr(game+0x276c3d0,0)
    local s,why=S.read(api,game);assert(not s and why=='waiting_for_runtime')
    ptr(game+0x276c3d0,mode);assert(S.read(api,game).id==103)
end)
test('temporary unreadable memory waits and recovers',function()
    local original=api.read;api.read=function()return nil end
    local s,why=S.read(api,game);assert(not s and why=='waiting_for_runtime')
    api.read=original;assert(S.read(api,game).id==103)
end)
test('concurrent candidate identity change retries without disabling the mod',function()
    word(enemy1+8,999)
    local s,why=S.read(api,game);assert(not s and why=='waiting_for_consistent_snapshot')
    word(enemy1+8,201);assert(S.read(api,game).id==103)
end)
test('mission exit yields a waiting state',function()
    word(mode+0x40,0);local s,why=S.read(api,game);assert(not s and why=='waiting_for_mission')
end)
return tostring(passed)..' snapshot tests passed'
